name: Deploy Django and React


on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and Deploy Django and React
    runs-on: ubuntu-latest
    steps:
      # 1. Chequear el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3


      # 2. Configurar Node.js para construir React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18


      # 3. Instalar y construir el proyecto React
      - name: Install and build React
        working-directory: frontend
        run: |
          npm install
          npm run build || (echo "Build failed!" && exit 1)


      # 4. Configurar Python para Django
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"


      # 5. Instalar dependencias de Django
      - name: Install Django dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # 6. Recolectar archivos estáticos de Django
      - name: Collect static files
        working-directory: backend
        run: |
          python manage.py collectstatic --noinput


      # 7. Preparar la rama de despliegue
      - name: Prepare deploy branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan deploy
          git reset --hard


      # 8. Mover los archivos generados directamente a la rama de deploy
      - name: Move build files to deploy branch
        run: |
          # Copiar archivos generados de React y Django directamente a la rama deploy
          cp -R frontend/dist/* ./  # Copiar archivos estáticos de React al root de la rama deploy
          cp -R backend/* ./  # Copiar archivos de Django al root de la rama deploy


      # 9. Crear el archivo .htaccess
      - name: Create .htaccess for React routing
        run: |
          echo "<IfModule mod_rewrite.c>" > .htaccess
          echo "RewriteEngine On" >> .htaccess
          echo "RewriteBase /" >> .htaccess
          echo "RewriteRule ^index\.html$ - [L]" >> .htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> .htaccess
          echo "RewriteRule . index.html [L]" >> .htaccess
          echo "</IfModule>" >> .htaccess


      # 10. Subir los cambios a la rama `deploy`
      - name: Commit and push to deploy branch
        run: |
          git add assets/* backend/* .htaccess index.html
          git commit -m "Deploy build $(date)"
          git push --force origin deploy
